services:
  - type: web
    name: franco-rpg
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: SUPABASE_URL
        value: https://nvflpadchqhozrmfvcyp.supabase.co
      - key: SUPABASE_KEY
        value: sb_publishable_hiBX0DdVbQ77_R-i7K9Vog_2gMq8kP0
